/******************************************************************************
* Author: Huynh Le Nhat Tam
* Date: 5th June 2022
*******************************************************************************/

#include <project.h>
#include "stdio.h"


uint8 compare_occured = 0;


/* The clock frequency for the PWM_Window. The PWM_Window clock frequency must be in KHz. 
 * Please update this define if the clock is updated in the TopDesign */
#define PWM_FREQ 30 //This seems to be the clock frequency that satisfies the requirement of displaying information 
//not too fast and time window that is short enough to capture the signal

/* Define for 1 second in terms of millisecond */
#define NO_OF_MSEC 1000

char uartout[20];
char isrcall[20] = "ISR is called \r\n";

CY_ISR_PROTO(myCompareisr);
int main()
{
	uint32 input_freq = 0;	//input_freq stores the value of the Doppler frequency generated by the radar sensor
        uint32 speed = 0;
	
	/* Variables to store the Period of the PWM_Window */
	static uint16 PWM_windowPeriod = 0;
	
	/* Variable to store the count value after capture */
	 static uint32 counter_countVal;
	
	/* Start the components */
	PWM_Window_Start();
	Counter_Start();
	LCD_Start();
	Clock_PWM_Start();
        UART_1_Start();
        Comp_1_Start();
        Opamp_1_Start();
        Opamp_2_Start();

	
	/* Calculate the time window during which the counter will count */
	PWM_windowPeriod = PWM_Window_ReadPeriod() ;
	
	/* Update the Time window value according to the clock given to the PWM_Window */
	PWM_windowPeriod = PWM_windowPeriod/ PWM_FREQ; 

	/* Enable the global interrupt */
	CYGlobalIntEnable;
			
	
    ISR_Compare_StartEx(myCompareisr);
for(;;)
    {		
		/* Check if the PWM interrupt has occurred
		 * The code works in such a way that, the PWM Compare event has an interrupt.
		 * The interrupt occurs for every second (Interrupt on Compare Event)
		 * The frequency calculation is done whenever the interrupt occurs */
		if (compare_occured == 1)
		{
			/* Read the Counter capture register */
			counter_countVal = Counter_ReadCapture();
			
			/* Convert the counts to frequency.
			 * Frequency is the number of counts in seconds
			 */
			input_freq = ((uint32)(NO_OF_MSEC * (uint32)counter_countVal) / (uint32)PWM_windowPeriod); 
			speed = input_freq/19.51; //Speed of light in air: 299 702 547 m/s = 1 078 929 169 km/h
						
			LCD_ClearDisplay(); //Clear the old displayed value
                        LCD_Position(0, 0);
	                LCD_PrintString("Frequency:");	
                        LCD_Position(0, 10);
			LCD_PrintU32Number(input_freq);
                        LCD_Position(0, 14);
                        LCD_PrintString("Hz");
			LCD_Position(1, 0);
                        LCD_PrintString("Speed: ");
	 		LCD_PrintU32Number(speed); 
			LCD_Position(1, 12);
			LCD_PrintString("km/h");	            
            
            
            
            sprintf(uartout,"Frequency: %lu Hz, Speed: %lu km/h \r\n", input_freq, speed);
            UART_1_PutString(uartout);
			
			/* Clear the interrupt flag */
			compare_occured = 0;
            
		}
    }
}

CY_ISR(myCompareisr)
{
  /* START ISR_Compare_Interrupt */

compare_occured = 1; // Set the flag to indicate occurence of the interrupt
UART_1_PutString(isrcall);
PWM_Window_ReadStatusRegister(); // Call the ReadStatusRegister to clear the Interrupt Status bit 


}
/* [] END OF FILE */
